version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "05:f8:7c:4b:f2:4d:9a:11:f8:61:5b:47:bb:38:d4:85"
      - checkout
      - run: scp -r * marineboudeau@marineboudeau.com:/home/marineboudeau/neogrid.org/
