version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "1a:14:f1:15:87:7c:2c:9b:fc:1a:43:47:0e:39:29:d5"
      - run: scp -r * marineboudeau@marineboudeau.com:/home/marineboudeau/neogrid.org/
